apiVersion: v1
kind: Service
metadata:
  name: mysql-db
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-db
  clusterIP: None  # Enables headless service, allowing direct access to MySQL pods