server:
  port: 8083

spring:
  application:
    name: blogapp
  datasource:
    url: jdbc:mysql://localhost:3306/blogdb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 60000  # 60 seconds
  jpa:
    hibernate:
      ddl-auto: update
